apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  labels:
    {{- include "modelcatalogue.labels" . | nindent 4 }}-php
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "modelcatalogue.selectorLabels" . | nindent 6 }}-php
  template:
    metadata:
      labels:
        {{- include "modelcatalogue.selectorLabels" . | nindent 8 }}-php
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: php
          image: "{{ .Values.images.php.repository }}:{{ .Values.images.php.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.images.php.pullPolicy }}
          resources: {}
          envFrom:
            - configMapRef:
                name: env
          volumeMounts:
            - name: config
              mountPath: /var/www/html/php
              readOnly: true
              subPath:
      #       - name: models
      #         mountPath: /usr/share/nginx/html/model/core
      #         readOnly: true
      #         subPath: core
      #       - name: models
      #         mountPath: /usr/share/nginx/html/xml
      #         readOnly: true
      #         subPath: xml
      volumes:
        - name: config
          configMap:
            name: php
      #   - name: models
      #     configMap:
      #       name: models
status: {}